In [1]:
from PyPDF2 import PdfReader
pdfpath="C:\\Users\\Ashar\\Desktop\\1197-31-ZEL-CPL-T-142.pdf"
reader = PdfReader(pdfpath)
page = reader.pages[0]
p1= page.extract_text()
print(p1)

 Sheet:
1 of 1

No.: Date:

From: To:
Client:
Project:
Subject:
Transmitted herewith are the following :

S. No.

1

Received By:

Date:
 For
Zishan Engineers (Pvt.) Ltd.
DETAIL ENGINEERING FOR KEROSENE HYDROTREATER (KHT)

Status
D E S C R I P T I O N
Drawings /
Documents No.
 Rev.
No.
Remarks
CALCULATION

-
      Zishan Engineers (Pvt.) Ltd.

T R A N S M I T T A L
47/F, Block 6, PECHS, Karachi-Pakistan

Tel:
 (92-21) 34393045-48 & 34310151-54
 Fax:
 (92-21) 34533430 & 34310158

E-mail:
 contact@zishanengineers.com
Website:
 www.zishanengineers.com

M/s. CNERGYICO PK LIMITED (CPL)
1197-31-ZEL-CPL-T-142

Tarique Ahmed
 June 17, 2022

Mr. Ikramullah Shah, Manager

1197-31-CAL-M-001
PIPETHICKNESSCALCULATIONFOR
SPECIFICATION012-07,015-08,015-01,015-10,
030-01, 030-11, 060-01, 060-02, 060-07, 060-09
 Advance
Copy

In [2]:
txt1=p1.splitlines()
print(txt1)

[' Sheet: ', '1 of 1', '', 'No.: Date:', '', 'From: To:', 'Client:', 'Project:', 'Subject:', 'Transmitted herewith are the following :', '', 'S. No.', '', '1', '', 'Received By:', '', 'Date:', ' For ', 'Zishan Engineers (Pvt.) Ltd.', 'DETAIL ENGINEERING FOR KEROSENE HYDROTREATER (KHT)', '', 'Status', 'D E S C R I P T I O N', 'Drawings /', 'Documents No.', ' Rev. ', 'No.', 'Remarks', 'CALCULATION', '', '-', '      Zishan Engineers (Pvt.) Ltd.', '', 'T R A N S M I T T A L', '47/F, Block 6, PECHS, Karachi-Pakistan', '', 'Tel:', ' (92-21) 34393045-48 & 34310151-54  ', ' Fax:', ' (92-21) 34533430 & 34310158', '', 'E-mail:', ' contact@zishanengineers.com  ', 'Website:', ' www.zishanengineers.com', '', 'M/s. CNERGYICO PK LIMITED (CPL)', '1197-31-ZEL-CPL-T-142', '', 'Tarique Ahmed', ' June 17, 2022', '', 'Mr. Ikramullah Shah, Manager', '', '1197-31-CAL-M-001', 'PIPETHICKNESSCALCULATIONFOR', 'SPECIFICATION012-07,015-08,015-01,015-10,', '030-01, 030-11, 060-01, 060-02, 060-07, 060-09', ' Advance ', 'Copy']

In [3]:
import tabula

In [4]:
tabula.environment_info()
dfs=tabula.read_pdf(pdfpath, stream=True)
#dfs[0]
data=dfs[0]
#data.shape
data

'pages' argument isn't specified.Will extract only from page 1 by default.

Python version:
    3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Java version:
    java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) Client VM (build 25.333-b02, mixed mode, sharing)
tabula-py version: 2.4.0
platform: Windows-10-10.0.19041-SP0
uname:
    uname_result(system='Windows', node='DESKTOP-HQ7AANG', release='10', version='10.0.19041', machine='AMD64', processor='Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')

,Unnamed: 0,Drawings /,Unnamed: 1,Unnamed: 2,Unnamed: 3,Rev.,Unnamed: 4,Unnamed: 5
0,S. No.,NaN,NaN,D E S C R I P T I O N,NaN,NaN,Status,Remarks
1,NaN,Documents No.,NaN,NaN,NaN,No.,NaN,NaN
2,1,1197-31-CAL-M-001,PIPE,THICKNESS CALCULATION FOR,NaN,-,Advance,NaN
3,NaN,NaN,SPECIFICATION,"012-07, 015-08, 015-01, 015-10,",NaN,NaN,Copy,NaN
4,NaN,NaN,"030-01, 030-11, 060-01, 060-02, 060-07, 060-09",NaN,NaN,NaN,NaN,NaN

In [34]:
pdfpath2='E:\\Downloads\\1197-31-ZEL-CPL-T-138.pdf'
dfs1=tabula.read_pdf(pdfpath2, stream=True)
data1=dfs1[0]
data1

'pages' argument isn't specified.Will extract only from page 1 by default.

,Unnamed: 0,Drawings /,Unnamed: 1,Rev.,Unnamed: 2,Unnamed: 3
0,S. No.,NaN,D E S C R I P T I O N,NaN,Status,Remarks
1,NaN,Documents No.,NaN,No.,NaN,NaN
2,1,1197-31-DSM-001,DATA SHEETS FOR LP ABSORBER (0306-56),1,IFC,NaN
3,2,1197-31-DSM-002,DATA SHEETS FOR HP ABSORBER (0306-54),1,IFC,NaN
4,3,1197-31-DSM-001-RA-,(CRS) DATA SHEETS FOR LP ABSORBER (0306-,-,-,NaN
5,NaN,CRS-001,56),NaN,NaN,NaN
6,4,1197-31-DSM-002-RA-,(CRS) DATA SHEETS FOR HP ABSORBER (0306-,-,-,NaN
7,NaN,CRS-001,54),NaN,NaN,NaN

In [ ]:
import pandas as pd

In [35]:
def read_table(data1):
    table1=pd.DataFrame()
    list1=data1.notnull()
    Documents=[]
    Descriptions=[]
    rev=[]
    Status=[]
    list2=[]
    list3=[]
    print(len(data))
    for i in range(1,len(data1)):
        doc=''
        des=''
        if list1.iloc[i,0]:
            startnum=i
            endnum=i
            #i+=1
            if endnum+1<len(list1):
                while ~list1.iloc[(endnum+1)%len(list1),0]:
                    if endnum+1<len(list1):
                        endnum+=1
                    else:
                        break

                    #i+=1
            for j in range(startnum,endnum+1):
                list2.append(j)
                doc+=str(data1.iloc[j,1])
                if data1.iloc[0,2]=='D E S C R I P T I O N':
                    if list1.iloc[j,2]:
                        des+=data1.iloc[j,2]
                else:
                    if list1.iloc[j,2]:
                        des+=data1.iloc[j,2]
                        if list1.iloc[j,3]:
                            des+=data1.iloc[j,3]
        if doc!='':
            Documents.append(doc)
        if des!='':
            Descriptions.append(des)
    return Documents,Descriptions

5
['1197-31-DSM-001', '1197-31-DSM-002', '1197-31-DSM-001-RA-CRS-001', '1197-31-DSM-002-RA-CRS-001']
['DATA SHEETS FOR LP ABSORBER (0306-56)', 'DATA SHEETS FOR HP ABSORBER (0306-54)', '(CRS) DATA SHEETS FOR LP ABSORBER (0306-56)', '(CRS) DATA SHEETS FOR HP ABSORBER (0306-54)']
[2, 3, 4, 5, 6, 7]

In [16]:
list1.iloc[len(list1)-1,0]

False